### ISSUE TITLE
Немного не достает документации

### ISSUE THREAD

**Issue by egorzot** [maximaster/tools.twig#10]
спасибо за решение!
Немного не хватает документации (особенно если не знаком с twig). 
Что бы хотелось
1. чтобы было описано, какие битриксовые функции и переменные компонента доступны в шаблоне (getMessage итд)
2. Кратко описать, как правильно создать лэнговый файл (т.е. расширение twig)
3. Пример кода или хотя бы ссылки на примеры

Всю эту информацию можно получить из блога (журов.ми), исходников и комментов к битриксовому модулю htc.twigintegrationmodule, но это занимает время :)

**Comment by mmjurov** [comment]
Спасибо, учтем в ближайшем будущем.

**Comment by mmjurov** [comment]
В последнем релизе расширил документацию. Примеры для работы с twig добавлять не стал, т.к. гораздо больше примеров можно найти на официальном сайте twig.

**Comment by egorzot** [comment]
гуд ! 👍
