### ISSUE TITLE
Новая версия twig

### ISSUE THREAD

**Issue by victorlapshev** [maximaster/tools.twig#11]
Вроде как обратная совместимость и все такое, может поменяете версию твига в зависимостях, попробуем

**Comment by vkryukov76** [comment]
"Новый" Твиг по-моему не дружит с `mbstring.func_overload`, а следовательно и с Битриксом

**Comment by victorlapshev** [comment]
Хм, не было проблем пока, может все таки попробуем?)

**Comment by mmjurov** [comment]
Битра имеет ограничение php 5.3+. В скором времени будет 5.6+
twig 2й версии работает только на php7
Нам пока еще придется работать с 5.6, чтобы сохранить совместимость с битрой, поэтому твиг пока останется первой версии.

Ну и плюс по хорошему надо проанализировать всю либу на предмет совместимости с твиг 2, стопудов используются возможности, которые стали deprecated. 

В планах вообще стоит перебрать всю либу по кусочкам и выпустить обновление с учетом накопленного опыта. Поэтому если есть какие-то предложения или багрепорты - пишите. Но вопрос с твиг2 пока закрыт
